#!/bin/bash
# Création des dictionnaires - SANS traduction (monolangue)

echo "============================================================"
echo "CRÉATION DES DICTIONNAIRES - MONOLANGUE"
echo "============================================================"

echo ""
echo "PIPELINE SIMPLIFIÉ (SANS TRADUCTION)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ┌─────────┐    ┌─────────┐    ┌─────────┐    ┌─────────┐"
echo "  │ Corpus  │───▶│ Extract │───▶│ Ranking │───▶│ Validat │"
echo "  │  brut   │    │   IA    │    │  Score  │    │ Experts │"
echo "  └─────────┘    └─────────┘    └─────────┘    └─────────┘"
echo ""
echo "  Pas de traduction = Pas de traducteurs = MOINS CHER"
echo ""

echo "COÛTS DÉTAILLÉS - DICTIONNAIRE GÉNÉRAL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Objectif : 254 (Tier 1) + 65 536 (Tier 2) = ~66 000 phrases"
echo ""
echo "  ┌────────────────────────┬─────────────┬──────────────────┐"
echo "  │ Poste                  │ Coût        │ Détail           │"
echo "  ├────────────────────────┼─────────────┼──────────────────┤"
echo "  │ Corpus SMS (achat)     │ 0-500€      │ Datasets publics │"
echo "  │ Extraction IA (GPT-4)  │ ~200€       │ ~1M tokens       │"
echo "  │ Nettoyage/Dédup        │ ~50€        │ Scripts auto     │"
echo "  │ Validation humaine     │ ~500€       │ Relecture 66K    │"
echo "  ├────────────────────────┼─────────────┼──────────────────┤"
echo "  │ TOTAL GÉNÉRAL          │ ~750-1250€  │                  │"
echo "  └────────────────────────┴─────────────┴──────────────────┘"
echo ""

echo "COÛTS DÉTAILLÉS - DICTIONNAIRE SPÉCIALISÉ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ┌────────────────────────┬─────────────┬──────────────────┐"
echo "  │ Poste                  │ Coût        │ Détail           │"
echo "  ├────────────────────────┼─────────────┼──────────────────┤"
echo "  │ Corpus spécialisé      │ ~500€       │ Terminologies    │"
echo "  │ Extraction IA          │ ~200€       │ ~1M tokens       │"
echo "  │ Nettoyage/Dédup        │ ~50€        │ Scripts auto     │"
echo "  │ Expert domaine         │ ~1000€      │ Validation pro   │"
echo "  ├────────────────────────┼─────────────┼──────────────────┤"
echo "  │ TOTAL PAR DOMAINE      │ ~1750€      │                  │"
echo "  └────────────────────────┴─────────────┴──────────────────┘"
echo ""

echo "RÉCAPITULATIF GLOBAL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ┌─────────────────────────────┬─────────────┐"
echo "  │ Configuration               │ Coût total  │"
echo "  ├─────────────────────────────┼─────────────┤"
echo "  │ Général seul                │ ~1 000€     │"
echo "  │ Général + 1 domaine         │ ~2 750€     │"
echo "  │ Général + 5 domaines        │ ~9 750€     │"
echo "  └─────────────────────────────┴─────────────┘"
echo ""
echo "  Comparaison AVEC traduction (10 langues) :"
echo ""
echo "  ┌─────────────────────────────┬─────────────┬─────────────┐"
echo "  │ Configuration               │ Sans trad.  │ Avec trad.  │"
echo "  ├─────────────────────────────┼─────────────┼─────────────┤"
echo "  │ Général seul                │ ~1 000€     │ ~3 000€     │"
echo "  │ Général + 5 domaines        │ ~9 750€     │ ~40 000€    │"
echo "  └─────────────────────────────┴─────────────┴─────────────┘"
echo ""
echo "  → Sans traduction : 4× moins cher !"
echo ""

echo "TEMPS DE CRÉATION ESTIMÉ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ┌────────────────────────┬─────────────┐"
echo "  │ Étape                  │ Durée       │"
echo "  ├────────────────────────┼─────────────┤"
echo "  │ Collecte corpus        │ 1-2 jours   │"
echo "  │ Extraction IA          │ 2-4 heures  │"
echo "  │ Nettoyage/Ranking      │ 1 jour      │"
echo "  │ Validation             │ 3-5 jours   │"
echo "  ├────────────────────────┼─────────────┤"
echo "  │ TOTAL (1 domaine)      │ ~1 semaine  │"
echo "  │ TOTAL (5 domaines)     │ ~3 semaines │"
echo "  └────────────────────────┴─────────────┘"
echo ""

echo "RÉSUMÉ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ┌─────────────────────────────────────────────────────────┐"
echo "  │  CRÉATION DICTIONNAIRE MONOLANGUE                      │"
echo "  │                                                         │"
echo "  │  • Général (66K phrases)     : ~1 000€                 │"
echo "  │  • + 1 domaine spécialisé    : +1 750€                 │"
echo "  │  • Temps : ~1 semaine/domaine                          │"
echo "  │                                                         │"
echo "  │  Configuration complète (5 domaines) :                 │"
echo "  │    Coût  : ~10 000€                                    │"
echo "  │    Temps : ~3 semaines                                 │"
echo "  │    Taille: ~6.5 Mo                                     │"
echo "  └─────────────────────────────────────────────────────────┘"
echo ""
