#!/bin/bash
# Estimation de compression avec dictionnaire 2 tiers

echo "============================================================"
echo "ESTIMATION COMPRESSION - DICTIONNAIRE 2 TIERS"
echo "============================================================"

echo ""
echo "STRUCTURE DU SYSTÈME 2 TIERS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  0x00-0xFD             → Tier 1 : 254 phrases (1 octet)"
echo "  0xFE + 2 octets       → Tier 2 : 65 536 phrases (3 octets)"
echo "  0xFF + len + texte    → Fallback : texte brut"
echo ""

echo "HYPOTHÈSES DE DISTRIBUTION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Tier 1 (254 phrases)    : 55% des messages"
echo "  Tier 2 (65 536 phrases) : 40% des messages"
echo "  Fallback (texte brut)   :  5% des messages"
echo ""
echo "  Note: Sans Tier 3, plus de messages vont dans Tier 2"
echo ""

echo "TAILLES MOYENNES DES PHRASES PAR TIER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Tier 1 : phrases courtes/fréquentes  → ~8 caractères moy."
echo "  Tier 2 : phrases moyennes à longues  → ~30 caractères moy."
echo "  Fallback : texte libre               → ~30 caractères moy."
echo ""

echo "CALCUL DE COMPRESSION (2 TIERS)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Pour 1000 messages :"
echo ""
echo "  ┌─────────┬─────────┬────────────┬────────────┬────────────┐"
echo "  │  Tier   │ Nb msg  │ Taille orig│ Taille enc │ Économie   │"
echo "  ├─────────┼─────────┼────────────┼────────────┼────────────┤"
echo "  │ Tier 1  │   550   │  4 400 o   │    550 o   │  3 850 o   │"
echo "  │         │         │ (550×8)    │  (550×1)   │            │"
echo "  ├─────────┼─────────┼────────────┼────────────┼────────────┤"
echo "  │ Tier 2  │   400   │ 12 000 o   │  1 200 o   │ 10 800 o   │"
echo "  │         │         │ (400×30)   │  (400×3)   │            │"
echo "  ├─────────┼─────────┼────────────┼────────────┼────────────┤"
echo "  │Fallback │    50   │  1 500 o   │  1 600 o   │  -100 o    │"
echo "  │         │         │ (50×30)    │(50×(1+1+30))│ (overhead) │"
echo "  ├─────────┼─────────┼────────────┼────────────┼────────────┤"
echo "  │ TOTAL   │  1000   │ 17 900 o   │  3 350 o   │ 14 550 o   │"
echo "  └─────────┴─────────┴────────────┴────────────┴────────────┘"
echo ""

# Calculs
ORIG=17900
ENC=3350
COMPRESSION=$((100 - (ENC * 100 / ORIG)))

echo "  RÉSULTAT : $ORIG o → $ENC o"
echo ""
echo "  ╔═══════════════════════════════════════════════════════╗"
echo "  ║  TAUX DE COMPRESSION MOYEN : ↓ ${COMPRESSION}%                   ║"
echo "  ╚═══════════════════════════════════════════════════════╝"
echo ""

echo "COMPARAISON 2 TIERS vs 3 TIERS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ┌────────────────┬─────────────┬─────────────┬───────────┐"
echo "  │ Système        │ Compression │ Complexité  │ Dico size │"
echo "  ├────────────────┼─────────────┼─────────────┼───────────┤"
echo "  │ 2 tiers        │    ↓ 81%    │   Simple    │  ~66K     │"
echo "  │ 3 tiers        │    ↓ 81%    │   Moyenne   │  ~16M     │"
echo "  └────────────────┴─────────────┴─────────────┴───────────┘"
echo ""
echo "  → Même compression, mais 2 tiers est PLUS SIMPLE !"
echo ""

echo "ANALYSE : POURQUOI 2 TIERS SUFFIT ?"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Avec 65 536 phrases dans Tier 2, on couvre :"
echo ""
echo "    • Toutes les salutations et formules de politesse"
echo "    • Questions/réponses courantes"
echo "    • Phrases du quotidien (RDV, retard, lieu...)"
echo "    • Expressions idiomatiques"
echo "    • Phrases professionnelles courantes"
echo ""
echo "  Le Tier 3 (16M) n'apporte que 1 octet d'économie"
echo "  pour des phrases TRÈS rares → overhead de 16M entrées !"
echo ""

echo "COÛT MÉMOIRE DU DICTIONNAIRE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Estimation (20 caractères moyens par phrase) :"
echo ""
echo "  ┌────────────────┬───────────────┬───────────────────────┐"
echo "  │ Système        │ Nb phrases    │ Taille dictionnaire   │"
echo "  ├────────────────┼───────────────┼───────────────────────┤"
echo "  │ 2 tiers        │ 254 + 65 536  │ ~1.3 Mo               │"
echo "  │ 3 tiers        │ + 16 millions │ ~320 Mo               │"
echo "  └────────────────┴───────────────┴───────────────────────┘"
echo ""
echo "  → 2 tiers = 250× moins de mémoire pour même résultat !"
echo ""

echo "SIMULATION MESSAGES INDIVIDUELS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

simulate() {
    local MSG="$1"
    local TIER="$2"
    local COST="$3"
    local LEN=${#MSG}
    local RATIO=$((100 - (COST * 100 / LEN)))
    printf "  %-40s %3d o → %d o  (↓%2d%%) [Tier %s]\n" "\"$MSG\"" $LEN $COST $RATIO "$TIER"
}

simulate "Salut" "1" "1"
simulate "OK" "1" "1"
simulate "Merci beaucoup!" "1" "1"
simulate "Je suis en retard de 10 minutes" "2" "3"
simulate "Tu peux m'envoyer l'adresse du resto?" "2" "3"
simulate "Désolé j'ai eu un imprévu au travail" "2" "3"
simulate "RDV 14h gare de Lyon sortie Diderot" "FB" "38"

echo ""

echo "RECOMMANDATION FINALE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ┌─────────────────────────────────────────────────────────┐"
echo "  │  ✓ 2 TIERS EST LE MEILLEUR CHOIX                       │"
echo "  │                                                         │"
echo "  │  • Même taux de compression (~81%)                      │"
echo "  │  • 250× moins de mémoire (1.3 Mo vs 320 Mo)            │"
echo "  │  • Plus simple à maintenir                              │"
echo "  │  • 65 536 phrases = largement suffisant                │"
echo "  └─────────────────────────────────────────────────────────┘"
echo ""
