#!/bin/bash
# Estimation de compression avec dictionnaire 3 tiers

echo "============================================================"
echo "ESTIMATION COMPRESSION - DICTIONNAIRE 3 TIERS"
echo "============================================================"

echo ""
echo "HYPOTHÈSES DE DISTRIBUTION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Basé sur l'analyse de corpus SMS typiques :"
echo ""
echo "  Tier 1 (253 phrases)    : 55% des messages"
echo "  Tier 2 (65 536 phrases) : 30% des messages"
echo "  Tier 3 (16M phrases)    : 10% des messages"
echo "  Fallback (texte brut)   :  5% des messages"
echo ""

echo "TAILLES MOYENNES DES PHRASES PAR TIER"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Tier 1 : phrases courtes/fréquentes  → ~8 caractères moy."
echo "           (Salut, OK, Merci, Oui, Non, À+, Biz...)"
echo ""
echo "  Tier 2 : phrases standards           → ~25 caractères moy."
echo "           (Je suis en retard, On se voit demain?...)"
echo ""
echo "  Tier 3 : phrases longues/rares       → ~45 caractères moy."
echo "           (Phrases spécifiques, contextuelles...)"
echo ""
echo "  Fallback : texte libre               → ~30 caractères moy."
echo "           (Noms propres, adresses, texte créatif...)"
echo ""

echo "CALCUL DE COMPRESSION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Pour 1000 messages :"
echo ""
echo "  ┌─────────┬─────────┬────────────┬────────────┬────────────┐"
echo "  │  Tier   │ Nb msg  │ Taille orig│ Taille enc │ Économie   │"
echo "  ├─────────┼─────────┼────────────┼────────────┼────────────┤"
echo "  │ Tier 1  │   550   │  4 400 o   │    550 o   │  3 850 o   │"
echo "  │         │         │ (550×8)    │  (550×1)   │            │"
echo "  ├─────────┼─────────┼────────────┼────────────┼────────────┤"
echo "  │ Tier 2  │   300   │  7 500 o   │    900 o   │  6 600 o   │"
echo "  │         │         │ (300×25)   │  (300×3)   │            │"
echo "  ├─────────┼─────────┼────────────┼────────────┼────────────┤"
echo "  │ Tier 3  │   100   │  4 500 o   │    400 o   │  4 100 o   │"
echo "  │         │         │ (100×45)   │  (100×4)   │            │"
echo "  ├─────────┼─────────┼────────────┼────────────┼────────────┤"
echo "  │Fallback │    50   │  1 500 o   │  1 600 o   │  -100 o    │"
echo "  │         │         │ (50×30)    │(50×(1+1+30))│ (overhead) │"
echo "  ├─────────┼─────────┼────────────┼────────────┼────────────┤"
echo "  │ TOTAL   │  1000   │ 17 900 o   │  3 450 o   │ 14 450 o   │"
echo "  └─────────┴─────────┴────────────┴────────────┴────────────┘"
echo ""

# Calculs
ORIG=17900
ENC=3450
COMPRESSION=$((100 - (ENC * 100 / ORIG)))

echo "  RÉSULTAT : $ORIG o → $ENC o"
echo ""
echo "  ╔═══════════════════════════════════════════════════════╗"
echo "  ║  TAUX DE COMPRESSION MOYEN : ↓ ${COMPRESSION}%                   ║"
echo "  ╚═══════════════════════════════════════════════════════╝"
echo ""

echo "COMPARAISON AVEC AUTRES MÉTHODES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  ┌────────────────────────┬─────────────┬─────────────────┐"
echo "  │ Méthode                │ Compression │ Remarque        │"
echo "  ├────────────────────────┼─────────────┼─────────────────┤"
echo "  │ Gzip (SMS court)       │  ↑ +50%     │ AUGMENTE taille │"
echo "  │ Gzip (texte long)      │  ↓ 60-80%   │ Bon si répétit. │"
echo "  │ Dico 1 niveau (1 oct)  │  ↓ ~90%     │ Limité 253 phr. │"
echo "  │ Dico 3 niveaux         │  ↓ ~81%     │ Flexible        │"
echo "  │ Huffman adaptatif      │  ↓ ~40-50%  │ Par caractère   │"
echo "  └────────────────────────┴─────────────┴─────────────────┘"
echo ""

echo "ANALYSE DE SENSIBILITÉ"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  Si le dictionnaire est bien construit (phrases fréquentes"
echo "  dans Tier 1), la compression peut atteindre :"
echo ""
echo "    Scénario optimiste (70% Tier1) : ↓ 87%"
echo "    Scénario réaliste  (55% Tier1) : ↓ 81%"
echo "    Scénario pessimiste (40% Tier1): ↓ 74%"
echo ""
echo "  Le facteur clé : qualité du dictionnaire Tier 1 !"
echo ""

echo "SIMULATION MESSAGES INDIVIDUELS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

simulate() {
    local MSG="$1"
    local TIER="$2"
    local COST="$3"
    local LEN=${#MSG}
    local RATIO=$((100 - (COST * 100 / LEN)))
    printf "  %-40s %3d o → %d o  (↓%2d%%) [Tier %s]\n" "\"$MSG\"" $LEN $COST $RATIO "$TIER"
}

simulate "Salut" "1" "1"
simulate "OK" "1" "1"
simulate "Je suis en retard de 10 minutes" "2" "3"
simulate "Tu peux m'envoyer l'adresse du resto?" "2" "3"
simulate "Désolé j'ai eu un imprévu au travail" "3" "4"
simulate "RDV 14h gare de Lyon sortie Diderot" "FB" "38"

echo ""
echo "  Note: Fallback = 0xFF + 1 octet longueur + texte brut"
echo ""
